apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudknowledges
spec:
  selector:
    matchLabels:
      app: cloudknowledges
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: cloudknowledges
    spec:
      containers:
      - name: cloudknowledges
        image: pkumarag/kubernetesproject
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
